# Generated by Django 5.0.1 on 2024-01-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulearnProject', '0002_vacancy_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='created_at',
            new_name='published_at',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_currency',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_from',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_to',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название навыка'),
        ),
    ]
