# Generated by Django 5.0.1 on 2024-01-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulearnProject', '0004_alter_vacancy_area_name_alter_vacancy_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название вакансии'),
        ),
    ]
