# Generated by Django 5.0.1 on 2024-01-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulearnProject', '0008_alter_vacancy_area_name_alter_vacancy_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('count', models.IntegerField(verbose_name='Количество вакансий')),
                ('count_fullstack', models.IntegerField(null=True, verbose_name='Количество вакансий fullstack')),
                ('average_salary', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Средняя зарплата')),
                ('average_salary_fullstack', models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='Средняя зарплата fullstack')),
                ('fraction_fullstack', models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='Доля вакансий fullstack')),
            ],
            options={
                'verbose_name': 'Статистика по востребованности',
                'verbose_name_plural': 'Статистика по востребованности',
            },
        ),
        migrations.CreateModel(
            name='GeographyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=200, verbose_name='Город')),
                ('count', models.IntegerField(verbose_name='Количество вакансий')),
                ('average_salary', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Средняя зарплата')),
                ('average_salary_fullstack', models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='Средняя зарплата fullstack')),
                ('fraction', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Доля вакансий')),
                ('fraction_fullstack', models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='Доля вакансий fullstack')),
            ],
            options={
                'verbose_name': 'Статистика по регионам',
                'verbose_name_plural': 'Статистика по регионам',
            },
        ),
    ]
