# Generated by Django 5.0.1 on 2024-01-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulearnProject', '0009_demandstats_geographystats'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('skill', models.CharField(max_length=100, unique=True, verbose_name='Навык')),
                ('count', models.IntegerField(verbose_name='Количество вакансий')),
                ('fraction', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Доля вакансий с навыком')),
                ('isFullstack', models.BooleanField(verbose_name='Fullstack')),
            ],
            options={
                'verbose_name': 'Статистика по навыкам',
                'verbose_name_plural': 'Статистика по навыкам',
            },
        ),
    ]
