# Generated by Django 5.0.1 on 2024-01-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulearnProject', '0010_skillstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandstats',
            name='year',
            field=models.IntegerField(unique=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='geographystats',
            name='area_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Город'),
        ),
    ]
