# Generated by Django 5.0.1 on 2024-01-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulearnProject', '0011_alter_demandstats_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographystats',
            name='fraction',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Доля вакансий'),
        ),
        migrations.AlterField(
            model_name='geographystats',
            name='fraction_fullstack',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Доля вакансий fullstack'),
        ),
    ]
