# Generated by Django 5.0.1 on 2024-01-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulearnProject', '0012_alter_geographystats_fraction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographystats',
            name='count_fullstack',
            field=models.IntegerField(null=True, verbose_name='Количество вакансий fullstack'),
        ),
    ]
