# Generated by Django 5.0.1 on 2024-01-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulearnProject', '0013_geographystats_count_fullstack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographystats',
            name='count_fullstack',
            field=models.IntegerField(default=0, verbose_name='Количество вакансий fullstack'),
            preserve_default=False,
        ),
    ]
