# Generated by Django 5.0.1 on 2024-01-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulearnProject', '0014_alter_geographystats_count_fullstack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillstats',
            name='skill',
            field=models.CharField(max_length=100, verbose_name='Навык'),
        ),
    ]
