# Generated by Django 5.0.1 on 2024-01-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulearnProject', '0015_alter_skillstats_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillstats',
            name='fraction',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Доля вакансий с навыком'),
        ),
    ]
