# Generated by Django 5.0.1 on 2024-01-23 01:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulearnProject', '0016_alter_skillstats_fraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название страницы')),
                ('path', models.CharField(max_length=100, unique=True, verbose_name='Путь')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Содержимое страницы')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
