# Generated by Django 5.0.1 on 2024-01-23 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulearnProject', '0018_skillstats_average_salary'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skillstats',
            unique_together={('year', 'skill', 'isFullstack')},
        ),
    ]
